name: Check for Bitrise Comment

on:
  issue_comment:
    types: [created]

jobs:
  run_tests:
    name: Trigger Build with comment
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: [ubuntu-latest]

    steps:
      - name: Get the pull request number
        id: pr_number
        env:
          BUILD_TRIGGER_TOKEN: ${{ secrets.BUILD_TRIGGER_TOKEN }}
        run: |
          echo ::set-output name=number::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: PR comment
        if: ${{ github.event.issue.pull_request && contains(fromJSON('["ci run tests", "retest", "run tests"]'), github.event.comment.body) }}
        run: |
          echo "$BITRISE_BUILD_TRIGGER_TOKEN"
